= Notes for working with DotNet Core

== Building CoreCLR

Both projects seem to have reasonable documentation to follow, although certain
portions are out of date:

On OS X:

* Builds on OS X require Homebrew to be placed in /usr/local, even though this not specified in the documentation. This primarily matters for the icu4c and openssl libraries.
* Mac OS X 10.11 is the minimum supported version. Ignore references to 10.10 (Yosemite).
* Although the mono installer is recommended on the website,

In general:

The instructions for NuGet are completely out of date:

* The nuget binary http://www.nuget.org/nuget.exe, as mentioned in the docs is version 2.8. The latests is version 3.3 (with version 3.4 due out soon). The download process now requires version 3 or later of NuGet (which is available from the website -- just download the command line tools).
* The particular packages listed in the NuGet XML don't seem to exist anymore. Running the command basically says as much.
* The updated feed is available at https://dotnet.myget.org/F/dotnet-core/api/v3/index.json and the feed is visible here: https://dotnet.myget.org/gallery/dotnet-core.

I updated to using the `dotnet` command line tool (which is present at `<repository>/Tools/dotnetcli/dotnet` after performing a full build.

I've had luck getting projects to download using the following project.json:

```
{
  "frameworks": {
    "dnxcore50": {}
  },

  "dependencies": {
    "System.Console": "4.0.0-*",
    "System.Diagnostics.Contracts": "4.0.1-*",
    "System.Diagnostics.Debug": "4.0.11-*",
    "System.Diagnostics.Tools": "4.0.1-*",
    "System.Globalization":  "4.0.11-*",
    "System.IO":  "4.1.0-*",
    "System.IO.FileSystem.Primitives": "4.0.1-*",
    "System.Reflection": "4.1.0-*",
    "System.Resources.ResourceManager": "4.0.1-*",
    "System.Runtime": "4.1.0-*",
    "System.Runtime.Extensions": "4.1.0-*",
    "System.Runtime.Handles": "4.0.1-*",
    "System.Runtime.InteropServices": "4.1.0-*",
    "System.Text.Encoding": "4.0.11-*",
    "System.Text.Encoding.Extensions": "4.0.11-*",
    "System.Threading": "4.0.11-*",
    "System.Threading.Tasks": "4.0.11-*"
  }
}
```

Downloading these libraries seems to work with the following command line:
`<repository>/tools/dotnetcli/dotnet restore project.json --projects projects --source http://https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`

This will throw all of the packages versions into the package.lock folder and the packages into the specified folder, in this case `packages`.

NOTE: I haven't yet attempted to run CoreCLR and see that the hello world example works and I don't know that what I've implemented here is sane. Attempt at your own peril!

=== Tooling

There are three different sets of tooling for DotNet Core: It's own commandline tools (e.g. `corerun`), DNX, NuGet, and DotNet CLI.

* `corerun` simply executes already compiled DotNet code. It assumes that all of the code needed has already been downloaded to disk.
* NuGet is a package manager. It downloads compiled code from a repository and places it on the local disk for corerun to use.
* DotNet CLI is integrates the DotNet Core tools and NuGet into a single interface which is easier to use. It allows for package management and also running programs.
* DNX is the DotNet execution environment. It is used to run an download packages. It is now deprecated in favor of the dotnet CLI tools.


=== Internationalization for Built-In Strings.

User facing strings in CoreCLR are placed in a resource file so that they can be internationalized. These resources get compiled into a library, mscorrc, which can then be used to internationalize them directly.

On non-Windows platforms, `src/nativeresources,` and `src/CMakeFiles.txt` collude in order to translate the resource file into a C++ file that is then turned into a library.

In order to look up these strings, one calls `PAL_GetResourceString` from `src/pal/locale/unicode.cpp,` which then uses an appropriate mechanism in order to resolve the issue.

On non OS X platforms, GNU GetText is used. On OS X, right now the normal string is returned. There should be a native implementation for OS X, but it seems that build choices preclude it; Mac OS X does not provide an internationalization story for ``command line tools'' as far as I know. It normally requires a bundle/framework or a full Cocoa app, but in this case we're only guaranteed to have a collection of dylibs.

On Windows platforms, the resources are used directly, side-stepping this code.

As far as I can tell, there's no story in the source tree for internationalizing mscorrc.

== Working with CMake

The minimum version supported version of CMake is 2.8.12.2, as per the source files. New features added to the CLR need to be compatible with this version.

== The Platform Abstraction Library
Present at `/src/pal` in the tree. Abstracts over the difference between different platforms. Only used by non-Windows platforms.

PAL has it's own separate set of tests that are not normally run. See `/src/pal/tests`. The repository has instructions on how to run them.

It has the following sections:

* `cruntime` More things from the standard C library. This time, the ``standard'' versions. These also generally replace the implementations of the core functions and behave closely to the Windows counterparts. Some of the methods mention being ``suspension safe'' and care about the currently executing thread. Not sure yet what this means.

* `debug` Implementation of the Win32 debugging functions on Unix.

* `handlemgr` Win32 API functions for manipulating the `HANDLE` opaque type.

* `include` The standard boring directory with all of the relevant PAL headers.

*  `init` A collection of functions that have no home because they're ot part of the Win 32 API. Also side-by-side API stuff in `sxs.cpp`

* `locale` Unicode, internationalization, and localization support for the CLR itself.

* `module` Win 32 and internal functions for loading executables and shared libraries. This is used for native libraries and not the Windows-specific ``PE'' format.

* `map` Virtual memory routines, along with support for memory mapping files into virtual memory.

* `memory` Routines for allocating heap memory. There are ``local'' memory allocation functions here, but they're the same as the heap ones. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa366596(v=vs.85).aspx[the MSDN documentation] for more details.

* `misc` A collection of miscellaneous code, mostly Win 32 APIs that don't fit into any of the other categories (e.g. MessageBox)

* `objmgr` Inter-process communication via ``objects''. (I'm not exactly sure what these are yet).

* `poll` An implementation of the standard poll function using select instead.

* `safecrt` A ``safe'' version of the standard C library. Reimplements many of the functions instead of using the host's library. Used on all unix platforms, although the implementation comes from windows.

* `shmemory` An implementation of shared memory primitives.

* `sync` Critical sections

* `synchmgr` Implementation of the Win32 API thread waiting functions and other internal infrastructure.

* `synchobj` Semaphores, mutexes, and event objects.

== IDES for working with .NET
* http://www.omnisharp.net/[Omnisharp]: For C# on OS X and Linux
* http://ionide.io[Ionide]: For F# on OS X and Linux.
* https://www.visualstudio.com/products/visual-studio-community-vs[Visual Studio Community]: A very capable IDE, for free. Windows only.
* https://code.visualstudio.com/[Visual Studio Code]: A lightweight IDE for Windows, OS X, and Linux.

I haven't yet had the opportunity to use any of these for hands on debugging or interaction with developing CoreCLR.
